version: 2

defaults: &defaults
  working_directory: ~/build
  docker:
    - image: circleci/node:14

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run test

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: NODE_ENV=production npm run build
      - save_cache:
          key: npm-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: npm-build-{{ .Branch }}-{{ .Revision }}
      - run: npm run deploy:chrome
      - run: npm run deploy:firefox

  deploy-firefox:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: npm-build-{{ .Branch }}-{{ .Revision }}
      - run: npm run deploy:firefox

workflows:
  version: 2
  development:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - test:
          requires:
            - init
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/

      - deploy-firefox:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-firefox)*/
            branches:
              ignore: /.*/
